### ISSUE TITLE
Can't use 4.0.3 with create-react-app/webpack 5

### ISSUE THREAD

**Issue by ggascoigne** [JohannesKlauss/react-hotkeys-hook#835] opened 2022-11-09 05:17 UTC
4.0.2 works fine, but on upgrading to 4.0.3 I get:

ERROR in ./node_modules/react-hotkeys-hook/dist/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./node_modules/react-hotkeys-hook/dist/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (1:18128):

Sticking to 4.0.2 avoids the issue.

Using react@18.2.0, react-scripts@5.0.1.

**Comment by ptmkenny** [comment] 2022-11-09 08:04
Same issue, also getting this prompt:

```
Add @babel/preset-react (https://github.com/babel/babel/tree/main/packages/babel-preset-react) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-jsx) to the 'plugins' section to en
```

However, I'm pretty sure this is unintentional because we shouldn't have to update npm config like this in a x.x.n release.

**Comment by martinstark** [comment] 2022-11-09 13:50
![image](https://user-images.githubusercontent.com/901824/200847264-9bc4ff53-8000-44ec-b5e8-50df24969aad.png)

CI scripts in our pr aren't liking it either, looks like a broken bundle.

**Comment by tmcw** [comment] 2022-11-09 15:24
This issue is most likely a duplicate of #795 - the recent 4.0.0 release was ESM-only.

**Comment by ggascoigne** [comment] 2022-11-09 15:58
I'd have thought so, except the other 4.0.x versions all work.

**Comment by JohannesKlauss** [comment] 2022-11-10 08:55
esbuild is not liking me. I'll try to get a fix working. Probably have to switch back to the old bundling system for now.

**Comment by naquarius** [comment] 2022-11-10 23:28
> ![image](https://user-images.githubusercontent.com/901824/200847264-9bc4ff53-8000-44ec-b5e8-50df24969aad.png)
> 
> CI scripts in our renovate pr aren't liking it either, looks like a broken bundle.

seeing this same issue here (4.0.3), when version locked to 4.0.2 i get `SyntaxError: Cannot use import statement outside a module`

**Comment by martinstark** [comment] 2022-11-11 09:55
> > ![image](https://user-images.githubusercontent.com/901824/200847264-9bc4ff53-8000-44ec-b5e8-50df24969aad.png)
> > CI scripts in our renovate pr aren't liking it either, looks like a broken bundle.
> 
> seeing this same issue here (4.0.3), when version locked to 4.0.2 i get `SyntaxError: Cannot use import statement outside a module`

I think you may be running into https://github.com/JohannesKlauss/react-hotkeys-hook/issues/795, and need to use 3.X instead

**Comment by nicksrandall** [comment] 2022-11-14 17:55
I have a PR in (#839) to fix this. I personally needed the fix ASAP so I published a fork on NPM with the changes: `@nicksrandall/react-hotkeys-hook`

**Closed** 2022-11-17 08:57 UTC
